#!/usr/bin/env python3
"""Generate TOFU factorial data from coherent author-level twin profiles.

This is deliberately separate from ``generate_ciru40.py``.  The legacy
row-wise generator and every FullAnswer training path remain reproducible.
Author-profile v2 fixes the experimental unit at one TOFU author block,
generates all target-relation twins jointly, and only then generates the
matched placebo cells for that frozen pair of author profiles.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parents[1]
DEFAULT_MANIFEST = ROOT / "ULD/configs/data/tofu_forget05_author_blocks.json"
DESIGN_VERSION = "tofu-author-profile-v2"
_DEFAULT_TEMPERATURE_KEYS: set[tuple[int, str]] = set()


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


ciru_data = load_module("author_factorial_ciru", ROOT / "ULD/uld/data/ciru.py")
f2r_generator = load_module(
    "author_factorial_json", SCRIPT_DIR / "generate_f2r_pairs.py"
)


TARGET_SYSTEM_PROMPT = """You construct one coherent fictional author twin for a
TOFU machine-unlearning factorial experiment. You receive all QA records for one
real benchmark author at once.

Create exactly one replacement author and one internally consistent profile fact
ledger. Then construct C01 for every source row jointly. C11 is immutable and is
not generated by you.

For each C01:
- preserve the source question's relation, response mode (affirmative, negative,
  qualified, or unavailable), answer format, number of stated facts, style,
  difficulty, and approximate question/answer lengths;
- replace every author-dependent cue, including implicit descriptions, birthplace,
  dates, titles, awards, genres, and biography details, with facts from the single
  replacement profile;
- do not merely swap the name while retaining facts from the target author;
- do not mention the target author or copy the source answer;
- do not add words such as fictional, synthetic, control, or benchmark.

The fact ledger is the source of truth: every C01 must cite one or more fact_id
values that entail its answer. Reuse the same fact whenever multiple questions ask
the same relation. Do not create contradictory values for the same relation.

Return one JSON object only:
{
  "target_entity": "exact required target author",
  "replacement_entity": "one new author name",
  "twin_profile": {
    "summary": "short coherent biography",
    "facts": [
      {"fact_id": "F01", "relation": "canonical relation", "value": "fact value"}
    ]
  },
  "target_cells": [
    {
      "source_id": "exact supplied source_id",
      "target_relation": "short canonical relation",
      "invariants": {
        "task": "factual QA", "style": "...", "difficulty": "...",
        "answer_format": "..."
      },
      "supporting_fact_ids": ["F01"],
      "C01": {"question": "...", "answer": "..."}
    }
  ]
}
"""


PLACEBO_SYSTEM_PROMPT = """You construct matched negative-control cells for an
author-level 2x2 factorial machine-unlearning experiment. The original author,
replacement author, immutable C11 rows, coherent twin fact ledger, and all C01
rows are frozen.

For every source_id create one placebo relation R=0 and both cells jointly:
- C10 uses the target author assignment; C00 uses the replacement author assignment.
- C10 and C00 ask the same placebo relation in parallel language.
- The placebo relation must differ from the row's target_relation and must not reveal,
  paraphrase, negate, or imply the C11 source answer.
- Match the C11/C01 response mode, answer format, fact count, style, difficulty, and
  approximate lengths. If a target answer is negative, qualified, or unavailable,
  keep that mode instead of forcing an affirmative answer.
- Preserve implicit-reference style when the source is implicit. Never add fictional,
  synthetic, control, benchmark, or public-information disclaimers.
- Keep every target-author placebo fact internally consistent across the block and
  every replacement-author placebo fact consistent with the frozen twin profile.

Return one JSON object only:
{
  "placebo_profile": {
    "facts": [
      {
        "fact_id": "P01", "relation": "canonical placebo relation",
        "target_value": "target-author control value",
        "replacement_value": "replacement-author control value"
      }
    ]
  },
  "placebo_cells": [
    {
      "source_id": "exact supplied source_id",
      "placebo_relation": "short canonical relation",
      "supporting_fact_ids": ["P01"],
      "C10": {"question": "...", "answer": "..."},
      "C00": {"question": "...", "answer": "..."},
      "placebo_rationale": "why this relation cannot reveal the target answer"
    }
  ]
}
"""


def normalise(value: object) -> str:
    return " ".join(str(value).casefold().split())


def load_manifest(path: Path) -> Dict:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    authors = manifest.get("authors")
    block_size = manifest.get("block_size")
    if not isinstance(block_size, int) or block_size <= 0:
        raise ValueError("manifest block_size must be a positive integer")
    if not isinstance(authors, list) or not authors:
        raise ValueError("manifest authors must be a non-empty list")
    expected = list(range(len(authors)))
    observed = [item.get("block_id") for item in authors]
    if observed != expected:
        raise ValueError(f"manifest block ids must be {expected}, got {observed}")
    if any(
        not isinstance(item.get("canonical_name"), str)
        or not item["canonical_name"].strip()
        for item in authors
    ):
        raise ValueError("every manifest author needs canonical_name")
    return manifest


def load_sources(split: str) -> List[Dict[str, str]]:
    from datasets import load_dataset

    dataset = load_dataset("locuslab/TOFU", split)["train"]
    return [
        {
            "source_id": f"{split}-{index:05d}",
            "question": row["question"],
            "answer": row["answer"],
        }
        for index, row in enumerate(dataset)
    ]


def group_author_blocks(sources: Sequence[Dict[str, str]], manifest: Mapping) -> List[Dict]:
    block_size = int(manifest["block_size"])
    authors = manifest["authors"]
    expected = block_size * len(authors)
    if len(sources) != expected:
        raise ValueError(f"manifest expects {expected} rows, got {len(sources)}")
    blocks = []
    for author in authors:
        block_id = int(author["block_id"])
        begin = block_id * block_size
        rows = list(sources[begin : begin + block_size])
        if len(rows) != block_size:
            raise ValueError(f"block {block_id} has {len(rows)} rows")
        canonical = author["canonical_name"].strip()
        mismatched = [
            row["source_id"]
            for row in rows
            if normalise(canonical)
            not in normalise(f"{row['question']} {row['answer']}")
        ]
        if mismatched:
            raise ValueError(
                f"manifest author {canonical!r} does not bind every row in block "
                f"{block_id}: {mismatched[:3]}"
            )
        blocks.append(
            {
                "block_id": block_id,
                "target_entity": canonical,
                "sources": rows,
            }
        )
    return blocks


def indexed_items(items: object, field: str, expected_ids: Iterable[str]) -> Dict[str, Dict]:
    if not isinstance(items, list):
        raise ValueError(f"{field} must be a list")
    result: Dict[str, Dict] = {}
    for item in items:
        if not isinstance(item, dict):
            raise ValueError(f"{field} entries must be objects")
        source_id = item.get("source_id")
        if not isinstance(source_id, str) or not source_id:
            raise ValueError(f"{field} entry missing source_id")
        if source_id in result:
            raise ValueError(f"duplicate {field} source_id: {source_id}")
        result[source_id] = item
    expected = set(expected_ids)
    observed = set(result)
    if observed != expected:
        missing = sorted(expected - observed)
        extra = sorted(observed - expected)
        raise ValueError(f"{field} coverage mismatch: missing={missing[:3]} extra={extra[:3]}")
    return result


def nonempty_qa(value: object, label: str) -> Dict[str, str]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be an object")
    for key in ("question", "answer"):
        if not isinstance(value.get(key), str) or not value[key].strip():
            raise ValueError(f"{label}.{key} must be a non-empty string")
    return {"question": value["question"].strip(), "answer": value["answer"].strip()}


def replace_exact_entity(text: str, target: str, replacement: str) -> tuple[str, int]:
    """Replace only the frozen canonical author name, case-insensitively."""
    return re.subn(re.escape(target), replacement, text, flags=re.IGNORECASE)


def validate_target_generation(block: Mapping, generated: Mapping) -> Dict:
    target = block["target_entity"]
    if normalise(generated.get("target_entity", "")) != normalise(target):
        raise ValueError(f"target_entity must equal manifest author {target!r}")
    replacement = generated.get("replacement_entity")
    if not isinstance(replacement, str) or not replacement.strip():
        raise ValueError("replacement_entity must be a non-empty string")
    replacement = replacement.strip()
    if normalise(replacement) == normalise(target):
        raise ValueError("replacement_entity must differ from target_entity")

    profile = generated.get("twin_profile")
    if not isinstance(profile, dict) or not isinstance(profile.get("facts"), list):
        raise ValueError("twin_profile.facts must be a list")
    facts: Dict[str, Dict] = {}
    for fact in profile["facts"]:
        if not isinstance(fact, dict):
            raise ValueError("profile facts must be objects")
        fact_id = fact.get("fact_id")
        if not isinstance(fact_id, str) or not fact_id.strip():
            raise ValueError("profile fact missing fact_id")
        if fact_id in facts:
            raise ValueError(f"duplicate profile fact_id: {fact_id}")
        facts[fact_id] = fact
    if not facts:
        raise ValueError("twin_profile must contain facts")

    source_ids = [row["source_id"] for row in block["sources"]]
    cells = indexed_items(generated.get("target_cells"), "target_cells", source_ids)
    entity_repairs = []
    for source in block["sources"]:
        item = cells[source["source_id"]]
        c01 = nonempty_qa(item.get("C01"), f"{source['source_id']}.C01")
        supporting = item.get("supporting_fact_ids")
        if (
            not isinstance(supporting, list)
            or not supporting
            or any(not isinstance(fact_id, str) or not fact_id.strip() for fact_id in supporting)
        ):
            raise ValueError(f"{source['source_id']} has invalid supporting_fact_ids")
        if not isinstance(item.get("target_relation"), str) or not item["target_relation"].strip():
            raise ValueError(f"{source['source_id']} missing target_relation")
        invariants = item.get("invariants")
        if not isinstance(invariants, dict) or any(
            not isinstance(invariants.get(key), str) or not invariants[key].strip()
            for key in ("task", "style", "difficulty", "answer_format")
        ):
            raise ValueError(f"{source['source_id']} has invalid invariants")
        for field in ("question", "answer"):
            repaired, count = replace_exact_entity(c01[field], target, replacement)
            if count:
                item["C01"][field] = repaired
                c01[field] = repaired
                entity_repairs.append(
                    {"source_id": source["source_id"], "field": f"C01.{field}", "count": count}
                )
        joined = normalise(f"{c01['question']} {c01['answer']}")
        if normalise(target) in joined:
            raise ValueError(f"{source['source_id']}.C01 leaks target author")
        if len(normalise(source["answer"])) >= 8 and normalise(source["answer"]) in joined:
            raise ValueError(f"{source['source_id']}.C01 copies source answer")
        substituted_source_answer, _ = replace_exact_entity(
            source["answer"], target, replacement
        )
        if (
            len(normalise(substituted_source_answer)) >= 8
            and normalise(substituted_source_answer) in joined
        ):
            raise ValueError(
                f"{source['source_id']}.C01 copies source answer after entity substitution"
            )
        # Preserve explicit-vs-implicit reference style.  If the canonical name
        # is explicit in one source field, its twin must be explicit there too.
        if normalise(target) in normalise(source["question"]):
            if normalise(replacement) not in normalise(c01["question"]):
                raise ValueError(f"{source['source_id']}.C01 loses explicit question identity")

    if entity_repairs:
        profile.setdefault("generation_repairs", {})[
            "replaced_exact_target_entity_in_c01"
        ] = entity_repairs

    references_by_fact: Dict[str, List[Dict]] = {}
    for item in cells.values():
        for fact_id in item["supporting_fact_ids"]:
            references_by_fact.setdefault(fact_id, []).append(item)

    created_fact_ids = []
    split_fact_ids: Dict[str, List[str]] = {}
    for fact_id, references in list(references_by_fact.items()):
        groups: Dict[tuple[str, str], List[Dict]] = {}
        for item in references:
            key = (
                normalise(item["target_relation"]),
                normalise(item["C01"]["answer"]),
            )
            groups.setdefault(key, []).append(item)
        if len(groups) > 1:
            new_ids = []
            for grouped_items in groups.values():
                suffix = min(
                    item["source_id"].rsplit("-", 1)[-1]
                    for item in grouped_items
                )
                new_id = f"{fact_id}__{suffix}"
                counter = 2
                while new_id in facts:
                    new_id = f"{fact_id}__{suffix}_{counter}"
                    counter += 1
                relation = grouped_items[0]["target_relation"].strip()
                value = grouped_items[0]["C01"]["answer"].strip()
                facts[new_id] = {
                    "fact_id": new_id,
                    "relation": relation,
                    "value": value,
                }
                profile["facts"].append(facts[new_id])
                for item in grouped_items:
                    item["supporting_fact_ids"] = [
                        new_id if current == fact_id else current
                        for current in item["supporting_fact_ids"]
                    ]
                new_ids.append(new_id)
            split_fact_ids[fact_id] = new_ids
            facts.pop(fact_id, None)
            profile["facts"] = [
                fact for fact in profile["facts"] if fact["fact_id"] != fact_id
            ]
        elif fact_id not in facts:
            item = references[0]
            facts[fact_id] = {
                "fact_id": fact_id,
                "relation": item["target_relation"].strip(),
                "value": item["C01"]["answer"].strip(),
            }
            profile["facts"].append(facts[fact_id])
            created_fact_ids.append(fact_id)

    if created_fact_ids or split_fact_ids:
        repairs = profile.setdefault("generation_repairs", {})
        if created_fact_ids:
            repairs["created_missing_fact_ids"] = sorted(created_fact_ids)
        if split_fact_ids:
            repairs["split_conflicting_fact_ids"] = split_fact_ids

    referenced_fact_ids = {
        fact_id
        for item in cells.values()
        for fact_id in item["supporting_fact_ids"]
    }
    unused_fact_ids = sorted(set(facts) - referenced_fact_ids)
    if unused_fact_ids:
        # Extra, unreferenced ledger entries do not define any experimental
        # cell.  Remove them deterministically rather than regenerating valid
        # QAs, and retain an explicit repair trace for the paper audit.
        profile["facts"] = [
            fact for fact in profile["facts"]
            if fact["fact_id"] in referenced_fact_ids
        ]
        repairs = profile.setdefault("generation_repairs", {})
        repairs["pruned_unreferenced_fact_ids"] = unused_fact_ids
        facts = {
            fact_id: fact for fact_id, fact in facts.items()
            if fact_id in referenced_fact_ids
        }

    # Recover a ledger field only when its referenced C01 rows determine one
    # unambiguous value.  This repairs harmless empty fields without inventing
    # evidence or changing any generated QA.  Conflicting references remain a
    # hard failure.
    for fact_id, fact in facts.items():
        references = [
            item for item in cells.values()
            if fact_id in item["supporting_fact_ids"]
        ]
        relation_values = {
            item["target_relation"].strip() for item in references
            if item["target_relation"].strip()
        }
        answer_values = {
            item["C01"]["answer"].strip() for item in references
            if item["C01"]["answer"].strip()
        }
        if not isinstance(fact.get("relation"), str) or not fact["relation"].strip():
            if len(relation_values) != 1:
                raise ValueError(
                    f"profile fact {fact_id} has no relation and references disagree"
                )
            fact["relation"] = next(iter(relation_values))
        if not isinstance(fact.get("value"), str) or not fact["value"].strip():
            if len(answer_values) != 1:
                raise ValueError(
                    f"profile fact {fact_id} has no value and references disagree"
                )
            fact["value"] = next(iter(answer_values))

    return {
        "target_entity": target,
        "replacement_entity": replacement,
        "twin_profile": profile,
        "target_cells": cells,
    }


def validate_placebo_generation(block: Mapping, generated: Mapping) -> Dict:
    profile = generated.get("placebo_profile")
    if not isinstance(profile, dict) or not isinstance(profile.get("facts"), list):
        raise ValueError("placebo_profile.facts must be a list")
    facts: Dict[str, Dict] = {}
    for fact in profile["facts"]:
        if not isinstance(fact, dict):
            raise ValueError("placebo profile facts must be objects")
        fact_id = fact.get("fact_id")
        if not isinstance(fact_id, str) or not fact_id.strip() or fact_id in facts:
            raise ValueError(f"invalid or duplicate placebo fact_id: {fact_id}")
        if any(
            not isinstance(fact.get(key), str) or not fact[key].strip()
            for key in ("relation", "target_value", "replacement_value")
        ):
            raise ValueError(f"placebo fact {fact_id} is incomplete")
        facts[fact_id] = fact
    if not facts:
        raise ValueError("placebo_profile must contain facts")
    source_ids = [row["source_id"] for row in block["sources"]]
    cells = indexed_items(generated.get("placebo_cells"), "placebo_cells", source_ids)
    for source in block["sources"]:
        item = cells[source["source_id"]]
        for cell in ("C10", "C00"):
            qa = nonempty_qa(item.get(cell), f"{source['source_id']}.{cell}")
            joined = normalise(f"{qa['question']} {qa['answer']}")
            if len(normalise(source["answer"])) >= 8 and normalise(source["answer"]) in joined:
                raise ValueError(f"{source['source_id']}.{cell} copies source answer")
        if not isinstance(item.get("placebo_relation"), str) or not item["placebo_relation"].strip():
            raise ValueError(f"{source['source_id']} missing placebo_relation")
        supporting = item.get("supporting_fact_ids")
        if (
            not isinstance(supporting, list)
            or not supporting
            or any(fact_id not in facts for fact_id in supporting)
        ):
            raise ValueError(
                f"{source['source_id']} has invalid placebo supporting_fact_ids"
            )
        if any(
            normalise(facts[fact_id]["relation"])
            != normalise(item["placebo_relation"])
            for fact_id in supporting
        ):
            raise ValueError(
                f"{source['source_id']} placebo fact relation does not match cell"
            )
        if not isinstance(item.get("placebo_rationale"), str) or not item["placebo_rationale"].strip():
            raise ValueError(f"{source['source_id']} missing placebo_rationale")
    return {"placebo_profile": profile, "placebo_cells": cells}


def assemble_author_block(
    block: Mapping,
    target_generation: Mapping,
    placebo_generation: Mapping,
    split: str,
    seed: int,
    model: str,
) -> Dict:
    target = validate_target_generation(block, target_generation)
    validated_placebo = validate_placebo_generation(block, placebo_generation)
    placebo = validated_placebo["placebo_cells"]
    profile_id = f"{split}:author-block-{block['block_id']:02d}:seed-{seed}"
    records = []
    for query_index, source in enumerate(block["sources"]):
        target_item = target["target_cells"][source["source_id"]]
        placebo_item = placebo[source["source_id"]]
        c01 = nonempty_qa(target_item["C01"], "C01")
        c10 = nonempty_qa(placebo_item["C10"], "C10")
        c00 = nonempty_qa(placebo_item["C00"], "C00")
        record = {
            "design_version": DESIGN_VERSION,
            "source_id": source["source_id"],
            "view": 0,
            "block_id": int(block["block_id"]),
            "query_index": query_index,
            "profile_id": profile_id,
            "canonical_target_entity": target["target_entity"],
            "source_question": source["question"],
            "source_answer": source["answer"],
            "target_entity": target["target_entity"],
            "replacement_entity": target["replacement_entity"],
            "target_relation": target_item["target_relation"],
            "placebo_relation": placebo_item["placebo_relation"],
            "identity_binding": {
                "C11": target["target_entity"],
                "C01": target["replacement_entity"],
                "C10": target["target_entity"],
                "C00": target["replacement_entity"],
            },
            "invariants": target_item["invariants"],
            "supporting_fact_ids": target_item["supporting_fact_ids"],
            "placebo_supporting_fact_ids": placebo_item["supporting_fact_ids"],
            "cells": {
                "C11": {"question": source["question"], "answer": source["answer"]},
                "C01": c01,
                "C10": c10,
                "C00": c00,
            },
            "changed_evidence": [
                f"target author profile -> {target['replacement_entity']} profile",
                *[f"profile fact -> {fact_id}" for fact_id in target_item["supporting_fact_ids"]],
            ],
            "placebo_rationale": placebo_item["placebo_rationale"],
            "generation": {
                "backend": "openai-compatible",
                "model": model,
                "design": DESIGN_VERSION,
                "experimental_unit": "author-block",
            },
        }
        errors = ciru_data.validate_ciru_unit(record)
        if errors:
            raise ValueError(f"{source['source_id']}: " + "; ".join(errors))
        record["audit"] = ciru_data.audit_ciru_unit(record)
        records.append(record)
    return {
        "design_version": DESIGN_VERSION,
        "block_id": int(block["block_id"]),
        "profile_id": profile_id,
        "target_entity": target["target_entity"],
        "replacement_entity": target["replacement_entity"],
        "twin_profile": target["twin_profile"],
        "placebo_profile": validated_placebo["placebo_profile"],
        "records": records,
    }


def request_json(client, args, system_prompt: str, payload: Mapping, label: str) -> Dict:
    last_error: BaseException | None = None
    feedback = ""
    modes = ["required", "prompt"] if args.json_mode == "auto" else [args.json_mode]
    temperature_key = (id(client), str(args.model))
    use_temperature = (
        args.temperature is not None
        and temperature_key not in _DEFAULT_TEMPERATURE_KEYS
    )
    for mode in modes:
        response_format_rejected = False
        attempt = 0
        while attempt < args.retries:
            attempt += 1
            try:
                request = {
                    "model": args.model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {
                            "role": "user",
                            "content": json.dumps(payload, ensure_ascii=False) + feedback,
                        },
                    ],
                }
                if use_temperature:
                    request["temperature"] = args.temperature
                if args.max_completion_tokens > 0:
                    request["max_completion_tokens"] = args.max_completion_tokens
                if mode == "required":
                    request["response_format"] = {"type": "json_object"}
                response = client.chat.completions.create(**request)
                return f2r_generator.extract_json(response.choices[0].message.content)
            except Exception as exc:
                last_error = exc
                if use_temperature and temperature_is_unsupported(exc):
                    # GPT-5-class Azure deployments can reject every explicit
                    # temperature except their API default.  This is a
                    # transport compatibility fallback, not a content retry.
                    use_temperature = False
                    _DEFAULT_TEMPERATURE_KEYS.add(temperature_key)
                    feedback = ""
                    attempt -= 1
                    print(
                        f"{label}: explicit temperature rejected; "
                        "retrying with API default",
                        flush=True,
                    )
                    continue
                if (
                    args.json_mode == "auto"
                    and mode == "required"
                    and f2r_generator.error_status(exc) == 400
                ):
                    response_format_rejected = True
                    break
                feedback = (
                    "\n\nReturn a corrected complete JSON object. The previous "
                    f"attempt for {label} failed: {type(exc).__name__}: {exc}"
                )
                print(
                    f"retry stage={label!r} request_attempt={attempt}/{args.retries} "
                    f"error={type(exc).__name__}",
                    flush=True,
                )
                time.sleep(min(2 ** (attempt - 1), 16))
        if not response_format_rejected:
            break
        print(f"{label}: JSON response_format rejected; retrying prompt-only", flush=True)
    raise RuntimeError(
        f"{label} failed after {args.retries} attempts: "
        f"{f2r_generator.describe_error(last_error)}"
    ) from last_error


def temperature_is_unsupported(exc: BaseException) -> bool:
    """Recognise APIs that require their default temperature to be omitted."""
    current: BaseException | None = exc
    seen = set()
    details = []
    while current is not None and id(current) not in seen:
        seen.add(id(current))
        details.append(str(current))
        body = getattr(current, "body", None)
        if body:
            details.append(str(body))
        current = current.__cause__ or current.__context__
    message = " ".join(details).casefold()
    return "temperature" in message and (
        "unsupported" in message or "only the default" in message
    )


def generate_block(client, args, block: Mapping) -> Dict:
    print(
        f"start_block block={block['block_id']} author={block['target_entity']}",
        flush=True,
    )
    source_payload = {
        "required_target_entity": block["target_entity"],
        "block_id": block["block_id"],
        "source_rows": block["sources"],
    }
    last_error: BaseException | None = None
    target = None
    validated_target = None
    for attempt in range(args.retries):
        print(
            f"start_stage block={block['block_id']} stage=target "
            f"attempt={attempt + 1}/{args.retries}",
            flush=True,
        )
        try:
            candidate = request_json(
                client, args, TARGET_SYSTEM_PROMPT, source_payload,
                f"block {block['block_id']} target profile",
            )
            validated_target = validate_target_generation(block, candidate)
            target = candidate
            print(f"stage_ready block={block['block_id']} stage=target", flush=True)
            break
        except Exception as exc:
            last_error = exc
            source_payload["hard_validation_feedback"] = str(exc)
            print(
                f"stage_reject block={block['block_id']} stage=target "
                f"attempt={attempt + 1}/{args.retries} error={exc}",
                flush=True,
            )
    if target is None:
        raise RuntimeError(f"block {block['block_id']} target validation failed: {last_error}")

    placebo_payload = {
        "block_id": block["block_id"],
        "target_entity": validated_target["target_entity"],
        "replacement_entity": validated_target["replacement_entity"],
        "twin_profile": validated_target["twin_profile"],
        "rows": [
            {
                **source,
                "target_relation": validated_target["target_cells"][source["source_id"]]["target_relation"],
                "C01": validated_target["target_cells"][source["source_id"]]["C01"],
                "invariants": validated_target["target_cells"][source["source_id"]]["invariants"],
            }
            for source in block["sources"]
        ],
    }
    placebo = None
    assembled = None
    for attempt in range(args.retries):
        print(
            f"start_stage block={block['block_id']} stage=placebo "
            f"attempt={attempt + 1}/{args.retries}",
            flush=True,
        )
        try:
            candidate = request_json(
                client, args, PLACEBO_SYSTEM_PROMPT, placebo_payload,
                f"block {block['block_id']} placebo profile",
            )
            validate_placebo_generation(block, candidate)
            # Run the complete downstream schema check inside the retry loop so
            # relation collisions, leakage, and four-cell length mismatches ask
            # the generator for a corrected block instead of discarding it.
            assembled = assemble_author_block(
                block, target, candidate, args.split, args.seed, args.model
            )
            placebo = candidate
            print(f"stage_ready block={block['block_id']} stage=placebo", flush=True)
            break
        except Exception as exc:
            last_error = exc
            placebo_payload["hard_validation_feedback"] = str(exc)
            print(
                f"stage_reject block={block['block_id']} stage=placebo "
                f"attempt={attempt + 1}/{args.retries} error={exc}",
                flush=True,
            )
    if placebo is None:
        raise RuntimeError(f"block {block['block_id']} placebo validation failed: {last_error}")
    return assembled


def load_valid_block(path: Path, block: Mapping, args) -> Dict | None:
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        records = data.get("records")
        if data.get("design_version") != DESIGN_VERSION or not isinstance(records, list):
            return None
        if len(records) != len(block["sources"]):
            return None
        expected = {source["source_id"] for source in block["sources"]}
        if {record.get("source_id") for record in records} != expected:
            return None
        if any(ciru_data.validate_ciru_unit(record) for record in records):
            return None
        return data
    except (OSError, ValueError, json.JSONDecodeError):
        return None


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--split", default="forget05_perturbed")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--profiles-output", type=Path)
    parser.add_argument("--state-dir", type=Path)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--model", required=True)
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--api-key-env", default="OPENAI_API_KEY")
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--max-completion-tokens", type=int, default=16000)
    parser.add_argument("--concurrency", type=int, default=2)
    parser.add_argument("--retries", type=int, default=4)
    parser.add_argument("--json-mode", choices=("auto", "required", "prompt"), default="auto")
    args = parser.parse_args()

    api_key = os.environ.get(args.api_key_env)
    if not api_key:
        raise SystemExit(f"Set {args.api_key_env} before generation")
    from openai import OpenAI

    manifest = load_manifest(args.manifest)
    if manifest.get("split") != args.split:
        raise SystemExit(
            f"Manifest is for {manifest.get('split')}, not requested split {args.split}"
        )
    blocks = group_author_blocks(load_sources(args.split), manifest)
    state_dir = args.state_dir or Path(str(args.output) + ".blocks")
    profiles_output = args.profiles_output or Path(str(args.output) + ".profiles.json")
    state_dir.mkdir(parents=True, exist_ok=True)

    completed: Dict[int, Dict] = {}
    pending = []
    for block in blocks:
        path = state_dir / f"block_{block['block_id']:02d}.json"
        cached = load_valid_block(path, block, args)
        if cached is None:
            pending.append(block)
        else:
            completed[block["block_id"]] = cached
            print(f"reuse block={block['block_id']} author={block['target_entity']}", flush=True)

    failures = []
    if pending:
        client = OpenAI(api_key=api_key, base_url=args.base_url)
        with ThreadPoolExecutor(max_workers=max(args.concurrency, 1)) as executor:
            futures = {executor.submit(generate_block, client, args, block): block for block in pending}
            for future in as_completed(futures):
                block = futures[future]
                try:
                    generated = future.result()
                    write_json(state_dir / f"block_{block['block_id']:02d}.json", generated)
                    completed[block["block_id"]] = generated
                    print(
                        f"valid_block={len(completed)}/{len(blocks)} "
                        f"block={block['block_id']} author={block['target_entity']}",
                        flush=True,
                    )
                except Exception as exc:
                    failures.append((block["block_id"], block["target_entity"], str(exc)))

    if failures or len(completed) != len(blocks):
        for block_id, author, error in failures:
            print(f"FAIL block={block_id} author={author}: {error}", file=sys.stderr)
        print(
            "Final JSONL was not written because the author-level design is incomplete. "
            f"Validated block checkpoints remain in {state_dir}.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    ordered = [completed[index] for index in range(len(blocks))]
    records = [record for block in ordered for record in block["records"]]
    if len(records) != len(blocks) * int(manifest["block_size"]):
        raise SystemExit("unexpected final record count")
    ciru_data.write_ciru_jsonl(args.output, records)
    write_json(
        profiles_output,
        {
            "design_version": DESIGN_VERSION,
            "split": args.split,
            "seed": args.seed,
            "manifest": str(args.manifest.resolve()),
            "profiles": [
                {
                    key: block[key]
                    for key in (
                        "block_id", "profile_id", "target_entity",
                        "replacement_entity", "twin_profile", "placebo_profile",
                    )
                }
                for block in ordered
            ],
        },
    )
    print(f"author_blocks={len(ordered)} units={len(records)} cells={4 * len(records)}")
    print(f"output={args.output}")
    print(f"profiles={profiles_output}")


if __name__ == "__main__":
    main()
